#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@Author: Kimmyzhang
@Email: 902227553.com 
@File: demo.py
@Time: 2017/11/27 15:07
"""

import tensorflow as tf

a = tf.constant([1, 2], name="a")
b = tf.constant([2, 3], name="b")
result = a + b

print(a.graph is tf.get_default_graph())
print(a.graph)
